"""action step provenance and knowledge documents

Revision ID: 696772289130
Revises: c84f23abf8e9
Create Date: 2026-07-07 07:09:52.480927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696772289130'
down_revision = 'c84f23abf8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=256), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    with op.batch_alter_table('action_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('last_verified', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_steps', schema=None) as batch_op:
        batch_op.drop_column('last_verified')
        batch_op.drop_column('source_url')

    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
