"""action step booking url

Revision ID: bbd14cfc2a95
Revises: 696772289130
Create Date: 2026-07-07 07:24:12.335341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd14cfc2a95'
down_revision = '696772289130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_url', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_steps', schema=None) as batch_op:
        batch_op.drop_column('booking_url')

    # ### end Alembic commands ###
